//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoopMusicPlayer.Assets {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoopMusicPlayer.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AllRepeat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllRepeat {
            get {
                return ResourceManager.GetString("AllRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always On Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AlwaysOnTop {
            get {
                return ResourceManager.GetString("AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BufferLength に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BufferLength {
            get {
                return ResourceManager.GetString("BufferLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DeviceInfo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeviceInfo {
            get {
                return ResourceManager.GetString("DeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DisableRepeat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisableRepeat {
            get {
                return ResourceManager.GetString("DisableRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ElapsedTime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ElapsedTime {
            get {
                return ResourceManager.GetString("ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frequency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LangNameMetadata {
            get {
                return ResourceManager.GetString("LangNameMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Latency {
            get {
                return ResourceManager.GetString("Latency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Loop {
            get {
                return ResourceManager.GetString("Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MoveToDown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MoveToDown {
            get {
                return ResourceManager.GetString("MoveToDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MoveToUp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MoveToUp {
            get {
                return ResourceManager.GetString("MoveToUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Player に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prev に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Random に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RandomRepeat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RandomRepeat {
            get {
                return ResourceManager.GetString("RandomRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RemainingTime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemainingTime {
            get {
                return ResourceManager.GetString("RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RepeatType に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RepeatType {
            get {
                return ResourceManager.GetString("RepeatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SeekTime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SeekTime {
            get {
                return ResourceManager.GetString("SeekTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SingleRepeat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SingleRepeat {
            get {
                return ResourceManager.GetString("SingleRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SpeakerCount に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpeakerCount {
            get {
                return ResourceManager.GetString("SpeakerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TimeFormat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UpdatePeriod に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdatePeriod {
            get {
                return ResourceManager.GetString("UpdatePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
    }
}
