name: CI

on:
  push:

jobs:
  build:
    name: Build-Desktop
    runs-on: ${{ matrix.config.runner }}
    strategy:
      matrix:
        config:
          - { platform: win-x86, runner: ubuntu-latest }
          - { platform: win-x64, runner: ubuntu-latest }
          - { platform: win-arm64, runner: ubuntu-latest }
          - { platform: osx-x64, runner: macos-latest }
          - { platform: osx-arm64, runner: macos-latest }
          - { platform: linux-x64, runner: ubuntu-latest }
          - { platform: linux-arm, runner: ubuntu-latest }
          - { platform: linux-arm64, runner: ubuntu-latest }
          - { platform: linux-musl-x64, runner: ubuntu-latest }
          - { platform: linux-musl-arm, runner: ubuntu-latest }
          - { platform: linux-musl-arm64, runner: ubuntu-latest }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Restore workloads
        run: |
          dotnet workload restore
      - name: Build
        run: |
          dotnet publish LoopMusicPlayer.Desktop -r ${{ matrix.config.platform }} -c Release -o publish --self-contained=true -p:UseAppHost=true
      - name: Make .app
        if: ${{ startsWith(matrix.config.platform, 'osx') }}
        run: |
          mv publish MacOS
          mv MacOS macOSAppAssets/LoopMusicPlayer/Contents
          mkdir publish
          mv macOSAppAssets/LoopMusicPlayer publish
          mv publish/LoopMusicPlayer publish/LoopMusicPlayer.app
      - name: Rename to AppImage
        if: ${{ startsWith(matrix.config.platform, 'linux') }}
        run: |
          mv publish/LoopMusicPlayer.Desktop publish/LoopMusicPlayer.Desktop.AppImage
      - name : Create Archive
        run: |
          cd publish
          zip LoopMusicPlayer-${{ matrix.config.platform }}.zip -r *
          mv *.zip ..
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LoopMusicPlayer-${{ matrix.config.platform }}
          path: ${{ github.workspace }}/*.zip


  android-build:
    name: Build-Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Restore workloads
        run: |
          dotnet workload restore
      - name: Build
        run: |
          cd ${{ github.workspace }}
          echo -n "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > ./release.keystore
          echo "${{ secrets.ANDROID_SIGNING_PASSWORD }}" > AndroidSigningPassword.txt
          dotnet publish LoopMusicPlayer.Android -c Release -p:AndroidKeyStore=true -p:AndroidSigningKeyStore=${{ github.workspace }}/release.keystore -p:AndroidSigningKeyAlias=${{ secrets.ANDROID_KEY_ALIAS }} -p:AndroidSigningKeyPass=file:${{ github.workspace }}/AndroidSigningPassword.txt -p:AndroidSigningStorePass=file:${{ github.workspace }}/AndroidSigningPassword.txt -o publish
      - name : Create Archive
        run: |
          cd publish
          zip LoopMusicPlayer-android.zip -r *Signed.apk
          mv *.zip ..
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LoopMusicPlayer-android
          path: ${{ github.workspace }}/*.zip

  # ios-build:
  #   name: Build-iOS
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: '8.x'
  #     - name: Restore workloads
  #       run: |
  #         dotnet workload restore
  #     - name: Build
  #       run: |
  #         dotnet publish LoopMusicPlayer.iOS -c Release -o publish
  #     - name : Create Archive
  #       run: |
  #         cd publish
  #         zip LoopMusicPlayer-ios.zip -r *
  #         mv *.zip ..
  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: LoopMusicPlayer-ios
  #         path: ${{ github.workspace }}/*.zip

  browser-build:
    name: Build-Browser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Restore workloads
        run: |
          dotnet workload restore
      - name: Build
        run: |
          dotnet publish LoopMusicPlayer.Browser -c Release -o publish
      - name : Create Archive
        run: |
          cd publish
          zip LoopMusicPlayer-browser.zip -r *
          mv *.zip ..
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: LoopMusicPlayer-browser
      #     path: ${{ github.workspace }}/*.zip

  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ${{ github.workspace }}/artifacts
        mv ./*/*.zip ./
        gh release create "${{ github.ref }}" ${{ github.workspace }}/artifacts/*.zip


