name: publish

on:
  push:


jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [win-x86, win-x64, osx-x64, linux-x64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}/LoopMusicPlayer
          dotnet restore
      - name: Build
        run: |
          cd ${{ github.workspace }}/LoopMusicPlayer
          dotnet build
