name: publish

on:
  push:
    tags:
      - "Ver.*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [win-x86, win-x64, osx-arm64, osx-x64, linux-x64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Install dependencies
        run: dotnet restore LoopMusicPlayer
      - name: Build
        run: dotnet publish LoopMusicPlayer -o ./bin/net8.0 -r ${{ matrix.platform }} --configuration Release --self-contained true

      - name: Remove File
        run: |
          rm -rf ./bin/net8.0/${{ matrix.platform }}

      - name: Rename App File
        if: matrix.platform == 'linux-x64'
        run: |
          cd ${{ github.workspace }}
          mv "./bin/net8.0/LoopMusicPlayer" "./bin/net8.0/LoopMusicPlayer.AppImage"

      - name: Create Archive
        run: |
          cd ${{ github.workspace }}
          zip LoopMusicPlayer-${{ matrix.platform }}.zip -r ./bin

      - uses: actions/upload-artifact@v3
        with:
          name: LoopMusicPlayer-${{ matrix.platform }}
          path: ${{ github.workspace }}/*.zip
        
  create-release:
    name: Create release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ${{ github.workspace }}/artifacts
        mv ./*/*.zip ./
        gh release create "${{ github.ref }}" ${{ github.workspace }}/artifacts/*.zip -t "${{ github.ref }}"

